services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    #   - mydb:/var/lib/mysql
  php:
    build: .
    working_dir: /var/www/html
    command: "php -S 0.0.0.0:80"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
# volumes:
#   mydb:
